# The URL the site will be built for
base_url = "https://nicholasboyko.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "nick boyko"
theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"  # Required for custom theme handling
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-light.css" }
]

[extra]
# Put all your custom variables here
mathjax = true
mathjax_dollar_inline_enable = true
fancy_code = true
dynamic_note = true
theme = "toggle"

socials = [
  { name = "linkedin", url = "https://www.linkedin.com/in/nicholasboyko/", icon = "linkedin" },
  { name = "github", url = "https://github.com/nickboyko/", icon = "github" },
]

menu = [
  # Configure menu bar here
  { name = "about", url = "/about", weight = 1 },
  { name = "contact", url = "/contact", weight = 2 },
  { name = "posts", url = "/posts", weight = 3 },
]   
